resources:
- name: py-world-git
  type: git
  source:
    uri: ((source-url))
    branch: ((branch))

- name: cf-devtest
  type: cf
  source:
    api: ((cf-api))
    username: ((username))
    password: ((password))
    organization: paas
    space: josh

jobs:
- name: get-resource
  public: true
  plan:
  - get: py-world-git
    trigger: true

- name: unit-test
  public: true
  plan:
  - get: py-world-git
    trigger: true
    passed: [get-resource]
  - task: run-unit-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: qnib/pytest
      inputs:
        - name: py-world-git           
      run:
        path: pytest
        args: 
        dir: py-world-git

- name: deploy-app
  public: true
  plan:
  - get: py-world-git
    passed: [unit-test]
    trigger: true
  - put: cf-devtest
    params:
      manifest: py-world-git/manifest.yml
      path: py-world-git

- name: acceptance-test
  public: true
  plan:
  - get: py-world-git
    trigger: true
    passed: [deploy-app]
  - task: acceptance-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: python
          tag: 2.7-jessie
      inputs:
        - name: py-world-git           
      run:
        path: py-world-git/acceptancetest.sh
      params:
        HOST: ((app-host))
        URL: ((app-url))
        NAME: "Rhi"
        