resources:
- name: py-world-git
  type: git
  source:
    uri: ((source-url))
    branch: ((branch))


jobs:
- name: get-resource
  public: true
  plan:
  - get: py-world-git
    trigger: true

- name: unit-test
  public: true
  plan:
  - get: py-world-git
    trigger: true
    passed: [get-resource]
  - task: run-unit-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: qnib/pytest
      inputs:
        - name: py-world-git           
      run:
        path: pytest
        args: 
        dir: py-world-git

- name: acceptance-test
  public: true
  plan:
  - get: py-world-git
    trigger: true
    passed: [unit-test]
  - task: acceptance-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: python
          tag: 2.7-jessie
      inputs:
        - name: py-world-git           
      run:
        path: py-world-git/acceptancetest.sh
      params:
        HOST: ((app-host))
        URL: ((app-url))
        NAME: "Rhi"
        